### ISSUE TITLE
Firefox: Map is blank

### ISSUE THREAD

**Issue by stdavis** [agrc/wri-web#110] opened 2015-10-01 15:27 UTC
![image](https://cloud.githubusercontent.com/assets/1326248/10225168/b0162b00-681e-11e5-8e30-49726812775d.png)

**Comment by steveoh** [comment] 2015-10-01 15:28
closed as duplicate of #108 and it's not just firefox.

**Closed by steveoh** 2015-10-01 15:28 UTC
Labels: bug

**Comment by stdavis** [comment] 2015-10-01 15:30
I'm not sure this is a duplicate. Firefox fails for me everytime. Other browsers are drawing fine for me 95% of the time. Tested Safari, Chrome, FF and IE11.

**Comment by steveoh** [comment] 2015-10-01 15:31
if you open the dev tools in firefox, it will start working if you set debug points or something. I can't remember what the trigger was.
